export declare const enum API_NAMESPACE {
    BASIC = "api/basic",
    SYSTEM = "api/system",
    TRANSACTION = "api/transaction"
}
export declare const enum BASIC_API_PATH {
    BASIC_SET_PASSWORD = "/setPassword",
    BASIC_GENERATE_GENESIS_BLOCK = "/generateGenesisBlock",
    BASIC_GET_BLOCK = "/getBlock",
    BASIC_GET_LAST_BLOCK = "/getLastBlock",
    BASIC_GET_TRANSACTION_TYPE = "/getTransactionType",
    BASIC_GET_TRANSACTIONS = "/getTransactions",
    BASIC_GET_BFCHAIN_VERSION = "/getBfchainVersion",
    BASIC_GET_BLOCK_CHAIN_STATUS = "/getBlockChainStatus",
    BASIC_GENERATE_SECRET = "/generateSecret",
    BASIC_CREATE_ACCOUNT = "/createAccount",
    BASIC_GET_ACCOUNT_PUBLICKEY = "/getAccountPublicKey",
    BASIC_GET_ACCOUNT_LAST_TRANSACTION = "/getAccountLastTransaction",
    BASIC_GET_ACCOUNT_LAST_TYPE_TRANSACTION = "/getAccountLastTypeTransaction",
    SET_KVSTORAGE_TEMP = "/setKVStorageTemp",
    GET_KVSTORAGE = "/getKVStorage"
}
export declare const enum SERVICE_API_PATH {
    SERVICE_USER_GET_PACKAGE_SOURCE = "/user/getPackageSource",
    SERVICE_USER_GET_UPLOAD_PACKAGE_TOKEN = "/user/getUploadPackageToken",
    SERVICE_USER_TEST = "/user/test",
    SERVICE_ADMIN_GET_PACKAGE_INFO = "/admin/getPackageInfo",
    SERVICE_ADMIN_GET_ADMIN_PACKAGE = "/admin/getAdminPackage",
    SERVICE_ADMIN_GET_MINER_MACHINE_DAPP_TYPE = "/admin/getMinerMachineDappType",
    SERVICE_ADMIN_GET_DOWNLOADED_PACKAGE_INFO = "/admin/getDownloadedPackageInfo",
    SERVICE_ADMIN_GET_ADMIN_UPLOAD_PACKAGE_TOKEN = "/admin/getAdminUploadPackageToken",
    SERVICE_ADMIN_SET_MINER_MACHINE_DAPP_TYPE = "/admin/setMinerMachineDappType",
    SERVICE_ADMIN_DOWNLOAD_PACKAGE = "/admin/downloadPackage",
    SERVICE_ADMIN_INSTALL_PACKAGE = "/admin/installPackage",
    SERVICE_ADMIN_CLEAR_DOWNLOAD_STATE = "/admin/clearDownloadState",
    SERVICE_ADMIN_UNINSTALL_AND_DELETE_PACKAGE = "/admin/uninstallAndDeletePackage",
    SERVICE_ADMIN_INSTALL_PACKAGE_HISTORY = "/admin/installPackageHistory",
    SERVICE_ADMIN_TEST = "/admin/test",
    SERVICE_AUTH_CODE = "/authCode",
    SERVICE_ADD_USER = "/addUser",
    SERVICE_ADD_SYSTEM_ADMINUSER = "/addSystemAdminuser",
    SERVICE_GET_PACKAGE_FILE = "/getPackageFile",
    SERVICE_GET_USER_PACKAGE = "/getUserPackage"
}
export declare const enum SYSTEM_API_PATH {
    SYSTEM_SAFETY_CLOSE = "/safetyClose",
    SYSTEM_SET_SYSTEM_KEY = "/setSystemKey",
    SYSTEM_VERIFY_SYSTEM_KEY = "/verifySystemKey",
    SYSTEM_ADD_SYSTEM_ADMIN = "/addSystemAdmin",
    SYSTEM_GET_SYSTEM_ADMIN = "/getSystemAdmin",
    SYSTEM_VERIFY_SYSTEM_ADMIN = "/verifySystemAdmin",
    SYSTEM_DELETE_SYSTEM_ADMIN = "/deleteSystemAdmin",
    SYSTEM_RESET_SYSTEM_ADMIN = "/resetSystemAdmin",
    SYSTEM_BINDING_ACCOUNT = "/bindingAccount",
    SYSTEM_GET_SYSTEM_DELEGATE = "/getSystemDelegate",
    SYSTEM_SET_SYSTEM_CONFIG = "/setSystemConfig",
    SYSTEM_GET_SYSTEM_CONFIG_INFO_DETAIL = "/getSystemConfigInfoDetail",
    SYSTEM_GET_RUNTIME_STATE = "/getRuntimeState",
    SYSTEM_MINING_MACHINE_INFO = "/miningMachineInfo",
    SYSTEM_GET_SYSTEM_MONITOR = "/getSystemMonitor",
    SYSTEM_GET_SYSTEM_LOGGER_TYPE = "/getSystemLoggerType",
    SYSTEM_GET_SYSTEM_LOGGER_LIST = "/getSystemLoggerList",
    SYSTEM_GET_SYSTEM_LOGGER_DETAIL = "/getSystemLoggerDetail",
    SYSTEM_DELETE_SYSTEM_LOGGER = "/delSystemLogger",
    SYSTEM_GET_EMAIL_ADDRESS = "/getEmailAddress",
    SYSTEM_SET_EMAIL_ADDRESS = "/setEmailAddress",
    SYSTEM_VERIFY_SYSTEM_SECRET = "/verifySystemSecret",
    SYSTEM_SET_SYSTEM_WHITELIST = "/setSystemWhitelist",
    SYSTEM_GET_SYSTEM_WHITELIST = "/getSystemWhitelist",
    SYSTEM_DELETE_SYSTEM_WHITELIST = "/delSystemWhitelist",
    SYSTEM_GET_PROCESS_CPU = "/getProcessCpu",
    SYSTEM_GET_PROCESS_MEMORY = "/getProcessMemory",
    SYSTEM_GET_PROCESS_NETWORK = "/getProcessNetwork",
    SYSTEM_STATUS = "/systemStatus",
    SYSTEM_PROCESS = "/systemProcess",
    SYSTEM_GET_SERVICE_INFO = "systemGetServiceInfo",
    SYSTEM_GET_SYSTEM_NODEINFO = "systemGetSystemNodeinfo",
    SYSTEM_GET_SERVICE_PEERINFO = "systemGetServicePeerinfo",
    SYSTEM_SET_SOCKET_EMIT_ENABLE = "systemSetSocketEmitEnable",
    SYSTEM_GET_INJECT_GENERATORS = "systemGetInjectGenerators",
    SYSTEM_SET_SYSTEM_DELEGATE_MULTI = "systemSetSystemDelegateMulti",
    SYSTEM_GET_SYSTEM_DELEGATE_DETAIL = "systemGetSystemDelegateDetail"
}
export declare const enum GENERATE_TRANSACTION_API_PATH {
    TR_COMMON = "/generate",
    TR_USERNAME = "/generate/username",
    TR_SIGNATURE = "/generate/signature",
    TR_DELEGATE = "/generate/delegate",
    TR_ACCEPT_VOTE = "/generate/acceptVote",
    TR_REJECT_VOTE = "/generate/rejectVote",
    TR_VOTE = "/generate/vote",
    TR_ISSUE_ASSET = "/generate/issueAsset",
    TR_TRANSFER_ASSET = "/generate/transferAsset",
    TR_DESTORY_ASSET = "/generate/destoryAsset",
    TR_GIFT_ASSET = "/generate/giftAsset",
    TR_GRAB_ASSET = "/generate/grabAsset",
    TR_TRUST_ASSET = "/generate/trustAsset",
    TR_SIGN_FOR_ASSET = "/generate/signForAsset",
    TR_TO_EXCHANGE_ASSET = "/generate/toExchangeAsset",
    TR_BE_EXCHANGE_ASSET = "/generate/beExchangeAsset",
    TR_DAPP = "/generate/dapp",
    TR_DAPP_PURCHASING = "/generate/dappPurchasing",
    TR_MARK = "/generate/mark",
    TR_LOCATION_NAME = "/generate/locationName",
    TR_SET_LNS_MANAGER = "/generate/setLnsManager",
    TR_SET_LNS_RECORD_VALUE = "/generate/setLnsRecordValue",
    TR_TO_EXCHANGE_SPECIAL_ASSET = "/generate/toExchangeSpecAsset",
    TR_BE_EXCHANGE_SPECIAL_ASSET = "/generate/beExchangeSpecAsset",
    TR_ISSUE_ENTITY_FACTORY = "/generate/issueEntityFactory",
    TR_ISSUE_ENTITY = "/generate/issueEntity",
    TR_DESTORY_ENTITY = "/generate/destoryEntity",
    TR_TO_EXCHANGE_ANY = "/generate/toExchangeAny",
    TR_BE_EXCHANGE_ANY = "/generate/beExchangeAny",
    TR_REGISTER_CHAIN = "/generate/registerChain",
    TR_EMIGRATE_ASSET = "/generate/emigrateAsset",
    TR_IMMIGRATE_ASSET = "/generate/immigrateAsset"
}
export declare const enum MIGRATE_CERTIFICATE_API_PATH {
    MIGRATE_CERTIFICATE_GENERATE = "/generate/migrateCertificate",
    MIGRATE_CERTIFICATE_FROM_AUTH_SIGNATURE = "/generate/migrateCertificateFromAuthSignature",
    MIGRATE_CERTIFICATE_TO_AUTH_SIGNATURE = "/generate/migrateCertificateToAuthSignature"
}
export declare const enum COMMON_API_PATH {
    VERIFY_ADDRESS = "/common/verifyAddress",
    VERIFY_PUBLICKEY = "/common/verifyPublicKey",
    GENERATE_KEYPAIR = "/common/generateKeypair",
    GENERATE_ACCOUNT = "/common/generateAccount",
    GENERATE_ADDRESS_BY_SECRET = "/common/generateAddressBySecret",
    GENERATE_ADDRESS_BY_PUBLICKEY = "/common/generateAddressByPublicKey",
    ASYMMETRIC_ENCRYPT = "/common/asymmetricEncrypt",
    ASYMMETRIC_DECRYPT = "/common/asymmetricDecrypt",
    CALC_TRANSACTION_MIN_FEE = "/common/calcTransactionMinFee",
    GENERATE_CIPHERTEXT_SIGNATURE = "/common/generateCiphertextSignature"
}
