export declare class SystemApi {
    private __networkHelper;
    private __SYSTEM_API_MAP;
    constructor(__networkHelper: BFMetaPcSdk.NetworkHelper);
    private __init;
    private __getSystemApi;
    safetyClose(argv: BFMetaPcSdk.System.SafetyCloseParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SafetyCloseResult>>;
    setSystemKey(argv: BFMetaPcSdk.System.SetSystemKeyParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SetSystemKeyResult>>;
    verifySystemKey(argv: BFMetaPcSdk.System.VerifySystemKeyParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.VerifySystemKeyResult>>;
    addSystemAdmin(argv: BFMetaPcSdk.System.AddSystemAdminParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.AddSystemAdminResult>>;
    getSystemAdmin(argv: BFMetaPcSdk.System.GetSystemAdminParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemAdminResult>>;
    verifySystemAdmin(argv: BFMetaPcSdk.System.VerifySystemAdminParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.VerifySystemAdminResult>>;
    deleteSystemAdmin(argv: BFMetaPcSdk.System.DeleteSystemAdminParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.DeleteSystemAdminResult>>;
    resetSystemAdmin(argv: BFMetaPcSdk.System.ResetSystemAdminParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.ResetSystemAdminResult>>;
    bindingAccount(argv: BFMetaPcSdk.System.BindingAccountParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.BindingAccountResult>>;
    getSystemDelegate(argv: BFMetaPcSdk.System.GetSystemDelegateParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemDelegateResult>>;
    setSystemConfig(argv: BFMetaPcSdk.System.SetSystemConfigParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SetSystemConfigResult>>;
    getSystemConfigInfoDetail(argv: BFMetaPcSdk.System.GetSystemConfigInfoDetailParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemConfigInfoDetailResult>>;
    getRuntimeState(argv: BFMetaPcSdk.System.GetRuntimeStateParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetRuntimeStateResult>>;
    miningMachineInfo(argv: BFMetaPcSdk.System.MiningMachineInfoParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.MiningMachineInfoResult>>;
    getSystemMonitor(argv: BFMetaPcSdk.System.GetSystemMonitorParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemMonitorResult>>;
    getSystemLoggerType(argv: BFMetaPcSdk.System.GetSystemLoggerTypeParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemLoggerTypeResult>>;
    getSystemLoggerList(argv: BFMetaPcSdk.System.GetSystemLoggerListParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemLoggerListResult>>;
    getSystemLoggerDetail(argv: BFMetaPcSdk.System.GetSystemLoggerDetailParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemLoggerDetailResult>>;
    deleteSystemLogger(argv: BFMetaPcSdk.System.DeleteSystemLoggerParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.DeleteSystemLoggerResult>>;
    getEmailAddress(argv: BFMetaPcSdk.System.GetEmailAddressParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetEmailAddressResult>>;
    setEmailAddress(argv: BFMetaPcSdk.System.SetEmailAddressParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SetEmailAddressResult>>;
    verifySystemSecret(argv: BFMetaPcSdk.System.VerifySystemSecretParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.VerifySystemSecretResult>>;
    setSystemWhiteList(argv: BFMetaPcSdk.System.SetSystemWhiteListParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SetSystemWhiteListResult>>;
    getSystemWhiteList(argv: BFMetaPcSdk.System.GetSystemWhiteListParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetSystemWhiteListResult>>;
    deleteSystemWhiteList(argv: BFMetaPcSdk.System.DeleteSystemWhiteListParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.DeleteSystemWhiteListResult>>;
    getProcessCPU(argv: BFMetaPcSdk.System.GetProcessCPUParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetProcessCPUResult>>;
    getProcessMemory(argv: BFMetaPcSdk.System.GetProcessMemoryParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetProcessMemoryResult>>;
    getProcessNetwork(argv: BFMetaPcSdk.System.GetProcessNetworkParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.GetProcessNetworkResult>>;
    systemStatus(argv: BFMetaPcSdk.System.SystemStatusParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SystemStatusResult>>;
    systemProcess(argv: BFMetaPcSdk.System.SystemProcessParams): Promise<BFMetaPcSdk.System.SystemApiReturn<BFMetaPcSdk.System.SystemProcessResult>>;
}
